In [ ]:
#Pregunta 1
import numpy as np

In [ ]:
#Pregunta 2
numbers = np.arange(1, 11)

print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Pregunta 3
print("Maximum value:", numbers.max())
print("Minimum value:", numbers.min())

Maximum value: 10
Minimum value: 1


In [ ]:
#Pregunta 4
zeros = np.zeros(5)

print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
#Pregunta 5
ones = np.ones(5)

print(ones)

[1. 1. 1. 1. 1.]


In [ ]:
#Pregunta 6
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#Pregunta 7
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Pregunta 8
print(matrix.shape)

(2, 3)
