In [1]:
import numpy as np

In [2]:
#Pregunta 1
numbers = np.arange(1, 11)

In [3]:
#Pregunta 2
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#Pregunta 3
print("Maximum value:", numbers.max())
print("Minimum value:", numbers.min())

Maximum value: 10
Minimum value: 1


In [5]:
#Pregunta 4
zeros = np.zeros(5)

print(zeros)

[0. 0. 0. 0. 0.]


In [6]:
#Pregunta 5
ones = np.ones(5)

print(ones)

[1. 1. 1. 1. 1.]


In [7]:
#Pregunta 6
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#Pregunta 7
print(matrix)


[[1 2 3]
 [4 5 6]]


In [8]:
#Pregunta 8
print(matrix.shape)

(2, 3)
